server:
  port: 8080

spring:  
  cloud:
    gateway:
      routes:
        - id: catalogRoute
          uri: lb://CATALOG-SERVICE
          predicates:
           - Path=/catalog/**
        - id: movieRoute
          uri: lb://MOVIE-SERVICE
          predicates:
           - Path=/movie/**
          filters:
            - AddRequestHeader=user-request-header, custom-user-request-header
            - AddResponseHeader=user-respons-header, custom-user-response-header 
